name: Trigger Netlify Build
on:
  schedule:
    # “At 20:00 on every day-of-week from Monday through Friday.”
    # https://crontab.guru/#0_20_*_*_1-5
    - cron: '0 1 * * 1'
jobs:
  build:
    name: Build Hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6540ad7cad7b2a6a8d9d44d1
